[package]
name = "rust-sudoku-game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
regex = "1.7.1"
serde_json = "1.0.94"
serde = "1.0.159"
serde_derive = "1.0.159"
chrono = "0.4.24"